mysite/urls.py
from django.contrib import admin
from django.urls import include, path
from debug_toolbar.toolbar import debug_toolbar_urls
from django.conf import settings

urlpatterns = [
    path("polls/", include("polls.urls")),
    path("tasks/", include("tasks.urls")),
    path("admin/", admin.site.urls),
] 
if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [
        path('__debug__/', include(debug_toolbar.urls)),  # Ruta requerida
    ]

polls/urls.py
from django.urls import path

from . import views

app_name = "polls"
urlpatterns = [
    path("", views.IndexView.as_view(), name="index"),
    path("<int:pk>/", views.DetailView.as_view(), name="detail"),
    path("<int:pk>/results/", views.ResultsView.as_view(), name="results"),
    path("<int:question_id>/vote/", views.vote, name="vote"),
]

tasks/urls.py
from django.urls import path

from . import views

app_name = "tasks"
urlpatterns = [
    path("", views.index, name="index"),
    path("<int:pk>/", views.details, name="detail"),
    path("create/", views.createTask, name="create"),
    path("created/", views.createConfirmation, name="created"),
    path("<int:pk>/finish/", views.finish, name="finish"),
]

polls/models.py
from django.db import models
from django.utils import timezone
import datetime
#from django.contrib import admin

class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField("date published")
    #@admin.display(
    #    boolean=True,
    #    ordering="pub_date",
    #    description="Published recently?",
    #)
    def __str__(self):
        return self.question_text
    
    def was_published_recently(self):
        return timezone.now() >= self.pub_date >= timezone.now() - datetime.timedelta(days=1)

class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

tasks/models.py
from django.db import models
from django.utils import timezone
import datetime

class MiExcepcion(Exception):
    pass
# Create your models here.
class Todo_task(models.Model):
    task_name = models.CharField(max_length=200)
    task_comments = models.CharField(max_length=20000)
    task_start_date = models.DateTimeField("start date")
    task_finished = models.BooleanField(default=False)
    task_finished_date = models.DateTimeField("finish date", null=True, blank=True)
    task_expected_finish_date = models.DateTimeField("expected finish date")

    def __str__(self):
        return self.task_name
    
    def task_not_finished_in_time(self):
        if self.task_finished:
            return self.task_expected_finish_date < self.task_finished_date
        else:
            raise MiExcepcion("No terminó")

polls/views.py
from polls.models import Question, Choice
from django.template import loader
from django.shortcuts import get_object_or_404, render
from django.db.models import F
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from django.views import generic
from django.utils import timezone
from .models import Choice, Question

#def index(request):
#    latest_question_list = Question.objects.order_by("-pub_date")[:5]
#    output = ", ".join([q.question_text + " (id=" + str(q.id) + ")" for q in latest_question_list])
#    return HttpResponse(output)

#def index(request):
#    latest_question_list = Question.objects.order_by("-pub_date")[:5]
#    template = loader.get_template("polls/index.html")
#    context = {
#        "latest_question_list": latest_question_list,
#    }
#    return HttpResponse(template.render(context, request))

#def index(request):
#    latest_question_list = Question.objects.order_by("-pub_date")[:5]
#    context = {"latest_question_list": latest_question_list}
#    return render(request, "polls/index.html", context)

class IndexView(generic.ListView):
    template_name = "polls/index.html"
    context_object_name = "latest_question_list"

    def get_queryset(self):
        """Return the last five published questions."""
        latest_question_list = Question.objects.filter(pub_date__lte=timezone.now()).order_by("-pub_date")[:5]
        return latest_question_list
    
    def get_context_data(self, **kwargs):
        # Obtén el contexto predeterminado de la clase padre
        context = super().get_context_data(**kwargs)
        # Agrega más datos al contexto
        context["hola"]="funciona bien?¿"
        context["total_questions"] = Question.objects.count()
        return context

#def detail(request, question_id):
#    question = get_object_or_404(Question, pk=question_id)
#    return render(request, "polls/detail.html", {"question": question})

class DetailView(generic.DetailView):
    model = Question
    template_name = "polls/detail.html"

    def get_queryset(self):
        """
        Excludes any questions that aren't published yet.
        """
        return Question.objects.filter(pub_date__lte=timezone.now())
#def results(request, question_id):
#    question = get_object_or_404(Question, pk=question_id)
#    return render(request, "polls/Results.html", {"question": question})

class ResultsView(generic.DetailView):
    model = Question
    template_name = "polls/results.html"

def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST["choice"])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form.
        return render(
            request,
            "polls/detail.html",
            {
                "question": question,
                "error_message": "You didn't select a choice.",
            },
        )
    else:
        selected_choice.votes = F("votes") + 1
        selected_choice.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse("polls:results", args=(question.id,)))

tasks/views.py
from django.shortcuts import render, get_object_or_404
from .models import Todo_task
from django.utils import timezone
from django.http import HttpResponse, HttpResponseRedirect, Http404
from django.urls import reverse

def index(request):
    some_near_date_task = Todo_task.objects.filter(task_finished=False).filter(task_start_date__lte = timezone.now()).order_by("-task_expected_finish_date")[:5]
    context = {
        "latest_task_list" : some_near_date_task,
        }
    return render(request,"tasks/index.html",context)

def details(request, pk):
    task = get_object_or_404(Todo_task ,pk=pk)
    if task.task_finished:
        is_overtime = task.task_finished_date > task.task_expected_finish_date
        overtime = task.task_finished_date - task.task_expected_finish_date
    else:
        is_overtime = task.task_expected_finish_date < timezone.now()
        overtime = timezone.now()-task.task_expected_finish_date
    return render(request, "tasks/details.html", {"task" : task,"overtime" : overtime, "is_overtime" : is_overtime })

def finish(requst, pk):
    task = get_object_or_404(Todo_task, pk=pk)
    if task != Http404: 
        task.task_finished = True
        task.task_finished_date = timezone.now()
        task.save()
    return HttpResponseRedirect(reverse("tasks:index"))

def createTask(request):
    return render(request,"tasks/create.html")

def createConfirmation(request):
    task_comments_a = request.POST['comentarios']
    print(task_comments_a)
    task_start_date_a = request.POST["task_start_date"]
    task_expected_finish_date_a = request.POST["task_expected_finish_date"]
    task_name_a = request.POST["task_name"]
    
    task=Todo_task.objects.create(task_name=task_name_a, task_comments=task_comments_a,
                                  task_start_date=task_start_date_a, task_expected_finish_date = task_expected_finish_date_a)
    print(task.task_comments)
    return HttpResponseRedirect(reverse("tasks:index"))

polls/templates/polls/Results.html
<h1>{{ question.question_text }}</h1>

<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
{% endfor %}
</ul>

<a href="{% url 'polls:detail' question.id %}">Vote again?</a>

polls/templates/polls/detail.html
<form action="{% url 'polls:vote' question.id %}" method="post">
    {% csrf_token %}
    <fieldset>
        <legend><h1>{{ question.question_text }}</h1></legend>
        {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
        {% for choice in question.choice_set.all %}
            <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
            <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
        {% endfor %}
    </fieldset>
    <input type="submit" value="Vote">
    </form>

polls/templates/polls/index.html
{% load static %}
</body>
<link rel="stylesheet" href="{% static 'polls/style.css' %}">
{% if latest_question_list %}
    <ul>
    {% for question in latest_question_list %}
        <li><a href="{% url 'polls:detail' question.id %}">{{ question.question_text }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}
<p>Total Questions: {{ total_questions }}</p>
<p>Funciona: {{ object_list }}</p>
</body>

polls/templates/polls/results.html
<h1>{{ question.question_text }}</h1>

<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
{% endfor %}
</ul>

<a href="{% url 'polls:detail' question.id %}">Vote again?</a>

tasks/templates/tasks/create.html
<body>
   <form action="{% url 'tasks:created' %}" method="post">
    {% csrf_token %}
    <fieldset>
        <legend><h1> Task Creation </h1></legend>
        <h3> Please complete the following blanks spaces to create a new Task: </h3>
        {%if error_message%}<p><strong>{{ error_message }}</strong></p>{%endif%}
        
        <label for="task_name">Task name:</label>
        <input type="text" id="task_name" name="task_name" maxlength="200" placeholder="Enter task name (max 200 chars)" required><br><br>
        
        <label for="comentarios">Task comments</label>
        <input type="text" id="comentarios" name="comentarios" maxlength="20000" placeholder="Enter comments (max 20000 chars)"> required<br><br>
    
        <label for="task_start_date">Start Date:</label>
        <input type="datetime-local" id="task_start_date" name="task_start_date" required><br><br>

        <label for="task_expected_finish_date">Expected finish Date:</label>
        <input type="datetime-local" id="task_expected_finish_date" name="task_expected_finish_date" required><br><br>
    </fieldset>
    <button type="submit">Submit</button>
   </form>

</body>

tasks/templates/tasks/details.html
<body>
    <legend><h1> {{ task.task_name }}</h1></legend>
    <p> comentarios: {{ task.task_comments }} </p>
    
    <p> {{ task.task_expected_finish_date }}</p>

    {% if not task.task_finished %}
        <p> task not finished </p>
        <a href="{% url 'tasks:finish' task.id %}"> Finalizar tarea</a>
    {% else %}
        <p> task finished in {{ task.task_finished_date}} </p>
    {% endif %}

    {% if is_overtime %}
            <p> task exceded by {{overtime}}</p>
    {%endif%}
</body>

tasks/templates/tasks/index.html
</body>
{% if latest_task_list %}
<ul>
    {% for task in latest_task_list %}
        <li><a href="{% url 'tasks:detail' task.id %}">{{ task.task_name }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No tasks left.</p>
{% endif %}
<a href="{% url 'tasks:create' %}">Do you want to create a new task?</a>
</body>